CREATE DATABASE IF NOT EXISTS `crud` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE crud;

CREATE TABLE  `employees` (
`id` INT AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 100 ) NOT NULL ,
`age` INT NOT NULL ,
) ENGINE = INNODB;
